services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build:
      context: ./back
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal


  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal


volumes:
  pgdata:
  front_dist:

networks:
  internal:
    driver: bridge
