name: Deploy with password SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH and deploy with password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'EOF'
            set -e
            echo "→ Переход в каталог /home/minecraft-server/SERVER/fri-proj"
            cd /home/minecraft-server/SERVER/fri-proj || (echo "❌ Не найден каталог /home/minecraft-server/SERVER/fri-proj" && exit 1)
          
            echo "→ Проверка: текущее содержимое"
            ls -la

            echo "→ Получение изменений из git"
            git pull origin main

            echo "→ Сборка Docker"
            docker compose build

            echo "→ Перезапуск контейнеров"
            docker compose up -d

            echo "✅ Деплой завершён"
          EOF
